# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals agent-laptop-1



steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python 3.x'

- task: CmdLine@2
  inputs:
    script: 'pip install - requirements.txt'
- task: AzureContainerApps@1
  inputs:
    appSourcePath: '$(Build.SourcesDirectory)/src'
    azureSubscription: 'Azure for Students(b1a9be0c-3adb-4b54-9b44-14b4d64810e1)'
    acrName: 'ev03'
    dockerfilePath: '$(Build.SourcesDirectory)/'
    containerAppName: 'evaluacion'